project:
  type: website

website:
  favicon: logo.png
  title: "残日留痕 | Residualsun"
  site-url: "https://residualsun.blog/"
  page-navigation: true
  back-to-top-navigation: true
  # reader-mode: true
  open-graph: true
  page-footer: 
    left: Powered by [Quarto](https://quarto.org/)
    right: © Copyright 2023 ❤️ Residualsun
  navbar:
    collapse-below: xxl
    title: false
    logo: logo.png
    logo-href: "https://residualsun.blog/"
    right:
      - about.qmd
      - text: 写作 #增加一个父级选项，和about并列
        menu:
          - text: 中文
            href: posts/cn/index.qmd
          - text: English
            href: posts/en/index.qmd
          - text: 所有 | All
            href: posts/index.qmd
            
      - text: R
        href: r/index.qmd
            
      - text: 链接
        href: link.qmd
            
      #- icon: github
      #  href: https://github.com/residualsun1
      #- icon: twitter
      #  href: https://twitter.com/Residualsun1
      
format:
  html:
    theme: zephyr
    css: styles.css
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    code-fold: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: 目录
    toc-location: left
    anchor-sections: true
    

editor: visual

comments:
  giscus:
    repo: residualsun1/Residualsun-English-blog