project:
  type: website

website:
  favicon: img/logo.png
  title: "Residualsun"
  site-url: "https://residualsun.blog/"
  page-navigation: true
  back-to-top-navigation: true
  # reader-mode: true
  open-graph: true
  
  navbar:
    # collapse-below: xxl
    title: Residualsun
    site-url: "https://residualsun.blog/"
    right:
      - text: 关于
        href: about.qmd
      - text: 中文博客
        href: posts-cn/index.qmd
      - text: 读书
        href: book-review/index.qmd
      - text: English writing
        href: posts-en/index.qmd
      - text: R
        href: r/index.qmd
            
      #- icon: github
      #  href: https://github.com/residualsun1
      #- icon: twitter
      #  href: https://twitter.com/Residualsun1
      
  page-footer:
    left: >-
      powered by [Quarto](https://quarto.org)
    right: © Copyright 2023 ❤️ Residualsun
      
format:
  html:
    theme: 
        - zephyr
    css: styles.css
    smooth-scroll: true
    #link-external-icon: false
    #link-external-newwindow: true
    code-fold: true
    citations-hover: true
    footnotes-hover: true
    #toc: true
    #toc-depth: 3
    #toc-title: 目录
    #toc-location: left
    #anchor-sections: true
    
execute: 
  freeze: auto
  
editor: source #在Rstudio中总是使用源代码模式。改为visual则是预览模式。

comments:
  giscus:
    repo: residualsun1/Residualsun-English-blog
    
incremental: true

lang: zh