project:
  type: website

website:
  title: "Guozheng"
  site-url: "https://residualsun.blog/"
  page-navigation: true
  page-footer: 
    left: Powered by [Quarto](https://quarto.org/)
    right: © Copyright 2023 ❤️ Residualsun
  navbar:
    right:
      - about.qmd
      - text: Post #增加一个父级选项，和about并列
        menu:
          - text: All posts #原来的Posts变成子级选项
            href: posts/index.qmd
          - text: English
            href: posts/en/index.qmd
          - text: 中文
            href: posts/cn/index.qmd
            
      - text: R
        href: r/index.qmd
            
      - text: link
        href: link.qmd
            
      - icon: github
        href: https://github.com/xxxxx
      - icon: twitter
        href: https://twitter.com/Residualsun1
      
format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

comments:
  giscus:
    repo: residualsun1/Residualsun-English-blog